### ISSUE TITLE
[Feature]: git commit after a package has been updated

### ISSUE THREAD

**Issue by Elsie19** [pacstall/pacup.py#13]
### Is your feature related to a problem? Please describe.

Pacup automates the updating of a package, but why not commit it. It seems a very useful thing, as this would help force conventional commit style commits, along with general ease of use.

### A clear and concise description of what you want to happen.

For Pacup to have a feature where it can git commit for you

### Describe alternatives you've considered

* Doing it manually
	- Tedius
* Setting up a shell script to run pacup and git commit
	- Could easily be automated with pacup into one tool

**Comment by wizard-28** [comment]
@Henryws How would you want it to behave when running this with multiple pacscripts? I don't want it to create multiple commits in the same branch.

**Comment by Elsie19** [comment]
We can check if multiple scripts are being updated and disable the feature.

**Comment by wizard-28** [comment]
@Henryws, It just should make the commit right? No branch changes?

**Comment by wizard-28** [comment]
# Discord conversation

> @wizard-28: I think I could make different branches for each of the pacscripts

https://discord.com/channels/839818021207801878/866673569521991700/957361808979664916

---

> @wizard-28: if multiple are specified

https://discord.com/channels/839818021207801878/866673569521991700/957361831893139486

---

> @Henryws: oh yeah

https://discord.com/channels/839818021207801878/866673569521991700/957361896737103963

**Comment by wizard-28** [comment]
Adding it via a new flag `-s, --ship`.

It'll do the following:
1. Update the pacscript
2. Change branches
3. Commit the changes
4. Push to origin
