### ISSUE TITLE
[Feature]: Installation via Pacstall

### ISSUE THREAD

**Issue by raxod502** [pacstall/pacup.py#16]
### Is your feature related to a problem? Please describe.

I notice the recommended way to install Pacup is via Pip. However, I avoid installing packages any way other than the distribution package manager (APT, in my case). If a package is unavailable on APT, I write a script to package it in the Debian format, and then install the resulting package through APT.

Of course, this sort of workflow is exactly what Pacstall is supposed to replace, leading to the question: would it be desired for Pacup to be installable via Pacscript? If so, I would be happy to contribute that.

### A clear and concise description of what you want to happen.

Ideally, I can run `pacstall -I pacup` and get started with Pacup immediately.

### Describe alternatives you've considered

We could also offer installable Debian packages as downloads from GitHub Releases for Pacup, which would remove the need for self-packaging for folks who like me would prefer to avoid installing software via any means other than APT.

**Comment by Elsie19** [comment]
We are planning to use nuitka for building binaries (#5), which we will then make a pacscript for it.

**Comment by raxod502** [comment]
OK, cool, I will build my own Debian package for the moment, and then migrate over to Pacscript once that work is completed. Thanks for the context.

**Comment by raxod502** [comment]
Script to build a working Debian package:

```bash
#!/usr/bin/env bash

set -euxo pipefail

pkg="${PWD}/pkg"

# https://github.com/pacstall/pacup/issues/17#issuecomment-1081343272
rm -rf "${pkg}"
pip3 install git+https://github.com/madkinsz/typer.git@b6efa2f8f40291fd80cf146b617e0ba305f6af3c pacup --root "${pkg}" --prefix /opt/pacup --ignore-installed

ver="$(cat "${pkg}"/opt/pacup/lib/python*/site-packages/pacup-*.dist-info/METADATA | grep "^Version:" | grep -Eo "[0-9ab.]+")"

install -d "${pkg}/usr/bin"
tee "${pkg}/usr/bin/pacup" <<EOF >/dev/null
#!/usr/bin/env bash
PYTHONPATH=/$(cd "${pkg}"; ls -d opt/pacup/lib/python*/site-packages) exec /opt/pacup/bin/pacup "\$@"
EOF
chmod +x "${pkg}/usr/bin/pacup"

install -d "${pkg}/DEBIAN"
tee "${pkg}/DEBIAN/control" <<EOF >/dev/null
Package: pacup
Version: ${ver}
Section: python
Priority: optional
Architecture: all
Maintainer: Radon Rosborough <radon.neon@gmail.com>
Description: Help maintainers update pacscripts
EOF

fakeroot dpkg-deb --build "${pkg}" "./pacup-${ver}.deb"
if dpkg -s pacup &>/dev/null; then
    sudo apt remove -y pacup
fi
sudo apt install -y "./pacup-${ver}.deb"
```

**Comment by wizard-28** [comment]
> Script to build a working Debian package:
> 
> ```shell
> #!/usr/bin/env bash
> 
> set -euxo pipefail
> 
> pkg="${PWD}/pkg"
> 
> # https://github.com/pacstall/pacup/issues/17#issuecomment-1081343272
> rm -rf "${pkg}"
> pip3 install git+https://github.com/madkinsz/typer.git@b6efa2f8f40291fd80cf146b617e0ba305f6af3c pacup --root "${pkg}" --prefix /opt/pacup --ignore-installed
> 
> ver="$(cat "${pkg}"/opt/pacup/lib/python*/site-packages/pacup-*.dist-info/METADATA | grep "^Version:" | grep -Eo "[0-9ab.]+")"
> 
> install -d "${pkg}/usr/bin"
> tee "${pkg}/usr/bin/pacup" <<EOF >/dev/null
> #!/usr/bin/env bash
> PYTHONPATH=/$(cd "${pkg}"; ls -d opt/pacup/lib/python*/site-packages) exec /opt/pacup/bin/pacup "\$@"
> EOF
> chmod +x "${pkg}/usr/bin/pacup"
> 
> install -d "${pkg}/DEBIAN"
> tee "${pkg}/DEBIAN/control" <<EOF >/dev/null
> Package: pacup
> Version: ${ver}
> Section: python
> Priority: optional
> Architecture: all
> Maintainer: Radon Rosborough <radon.neon@gmail.com>
> Description: Help maintainers update pacscripts
> EOF
> 
> fakeroot dpkg-deb --build "${pkg}" "./pacup-${ver}.deb"
> if dpkg -s pacup &>/dev/null; then
>     sudo apt remove -y pacup
> fi
> sudo apt install -y "./pacup-${ver}.deb"
> ```

For the next release of PacUp, I'll get the nuitka builds working, and package the built file in a debian archive and release it. Also I'll be making a pacscript for it.

**Comment by wizard-28** [comment]
Done in https://github.com/pacstall/pacstall-programs/pull/1748
