### ISSUE TITLE
[Bug]: version `GLIBC_2.36' not found

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacup.py#202]
### What happened?

```
[:~/Downloads] % wget https://github.com/pacstall/pacup/releases/download/2.1.0/pacup -q         
[:~/Downloads] % chmod +x ./pacup
[:~/Downloads] % ./pacup                                                                         
[581031] Error loading Python lib '/tmp/_MEIErZg9N/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.36' not found (required by /tmp/_MEIErZg9N/libexpat.so.1)

```
### What do you expect to happen?

Be able to execute pacup in a jammy LTS base 'GLIBC_2.35'

### Which pacscripts are affected?

All

### Steps to reproduce

Execute release binary of pacup in a jammy LTS base

### Version

Latest Release

**Comment by Elsie19** [comment]
Sorry for the late response!!!! Have you since updated to mantic and seen a difference?

**Comment by Zahrun** [comment]
I am still using a jammy base on my main machine and the issue is still valid there
Actually I am using pacup from pip, just wanted to open this issue to inform that the compiled version available from github release does not work with Ubuntu LTS

**Comment by Zahrun** [comment]
Which also affects `pacstall -I pacup-bin`

**Comment by Elsie19** [comment]
Can you try with https://cdn.discordapp.com/attachments/839949845359624223/1190300297927606282/pacup?ex=65a14c89&is=658ed789&hm=dc4cc5b3f8faec6cf306ed240be96c37f766b05e571c4b9e3e37cb8b81c07e35&
this file

**Comment by Zahrun** [comment]
[419103] Error loading Python lib '/tmp/_MEIVBAE5s/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIVBAE5s/libpython3.11.so.1.0)

**Comment by Elsie19** [comment]
Can you please run `ldd --version` and send the text back?

**Comment by Zahrun** [comment]
ldd (Ubuntu GLIBC 2.35-0ubuntu3.5) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by srd424** [comment]
It looks like the 2.1.0 release was built elsewhere and uploaded, rather than being generated by GHA. I've forked the repo and run the CD workflow and the generated binary works fine on jammy. I think someone just needs to kick GHA to rebuild + release?

**Comment by Elsie19** [comment]
> It looks like the 2.1.0 release was built elsewhere and uploaded, rather than being generated by GHA. I've forked the repo and run the CD workflow and the generated binary works fine on jammy. I think someone just needs to kick GHA to rebuild + release?

ok thanks for letting me know

**Comment by srd424** [comment]
I needed #271 to actually produce a working binary, as well :)

**Comment by Elsie19** [comment]
Hey @srd424 can you test https://github.com/pacstall/pacup/actions/runs/7945370506/artifacts/1253933928

**Comment by srd424** [comment]
That sorts the glibc error, instead gives:
```
AttributeError: 'AsyncLock' object has no attribute '_anyio_lock'
[4056972] Failed to execute script '__main__' due to unhandled exception!
```
Which is the error I've been chasing down for the last 4 hours! (I'm not a python person so this stuff takes me forever.) #271 seems to fix it for me, not 100% sure why (see detail on the PR.)

**Comment by Elsie19** [comment]
@srd424 @Zahrun https://github.com/pacstall/pacup/actions/runs/7945464415/artifacts/1253946854

Test please!

**Comment by srd424** [comment]
Looks good!

**Comment by srd424** [comment]
New binary has successfully updated [oil](https://pacstall.dev/packages/oil) for me, which is what I actually sat down to do yesterday afternoon, anyway :)

**Comment by Elsie19** [comment]
Awesome, I'll get one of my python minions to make a new pacup release 😁

**Comment by Elsie19** [comment]
Fixed in https://github.com/pacstall/pacstall-programs/commit/1c21e44b4e2cfe2b4dc4144e4af2a8bf08b5a09e

**Comment by Zahrun** [comment]
Can confirm 👍
Thanks
