### ISSUE TITLE
[Feature]: Support for multiple URLs and hashes

### ISSUE THREAD

**Issue by Zahrun** [pacstall/pacup.py#74]
### Is your feature related to a problem? Please describe.

Since pacstall supports Ubuntu and Debian, and ideally different releases LTS/latest Stable/Unstable/Testing, for some packages, it is required to use multiple urls and each can have a different hash.
See for example https://github.com/pacstall/pacstall-programs/blob/master/packages/fsearch-deb/fsearch-deb.pacscript

### A clear and concise description of what you want to happen.

Would be nice if pacup could update these urls and hashes from repology version change

Maybe it could detect a case structure and evaluate url and hash separately for each case

**Comment by wizard-28** [comment]
Not possible currently due to the way pacup parses the pacscript. Maybe in the future I'll implement this.

**Comment by Elsie19** [comment]
Will be done soon, when our Perl rewrite is done. Should be in less than a week with the release of 5.0.0.
